### ISSUE TITLE
No module named 'timedelta'

### ISSUE THREAD

**Issue by rickenrocker24** [chanzer0/nfl_optimizer#1]
Hello,
I ran into an error when trying to run your opto...any idea? See screenshot

![image](https://user-images.githubusercontent.com/17555582/103964355-17780400-5110-11eb-9409-03b737bf147a.png)

**Comment by chanzer0** [comment]
Hi rickenrocker24, the readme wasn't clear. I didn't include the list of packages necessary for the script to run. You must install the following packages:

- PuLP (pip install pulp)
- timedelta (pip install timedelta)
- numpy (pip install numpy)

There may be others as well. If you encounter this error, it should be solveable by installing the module listed as missing. I will update the README to include these dependencies.

**Comment by rickenrocker24** [comment]
Got it thank you that worked...

1. Can you provide me an example of the GPP command line? I tried "python
.\main.py fd sim 100 1" but it does not output....Opto works, just not Sim

2. How can we go by the other non-main slates? edit the excel file to
prefer slates?

**Comment by chanzer0** [comment]
Glad that worked for you. I'm currently working on adding simulations for both FD and DK, but they aren't currently implemented, so that is not an error on your part. I'm also working on non-main slates, such as showdown on DK and FD, but those too are works in progress. Stay tuned and watch for updates! GPP sims should be implemented soon, followed by showdown/small slates. For fanduel, any contest that has PG,PG,SG,SG,SF,SF,PF,PF,C roster slots should work with the `opto` command, so long as you provide the correct `player_ids.csv` and `projections.csv`

Thank you for addressing the issues, I hope things are okay in the meantime.
