### ISSUE TITLE
No module named 'nfl_optimizer'

### ISSUE THREAD

**Issue by BeeRabbits** [chanzer0/nfl_optimizer#8]
Hello! Great work on this, has been fun to play with so far! However ran into issues with 

![image](https://user-images.githubusercontent.com/120123974/206516506-461f8e1d-c4af-4aeb-830f-e58226485545.png)

Im assuming because of  import nfl_optimizer within import.py but removing that fixes.

**Comment by chanzer0** [comment]
Good catch, I must've pushed up when I was in the process of moving my NFL optimizer to a different repository.

This issue should be fixed in my next push, but in the meantime I will leave this issue open for others to reference if they have the same error. The fix is as simple as removing the the line in `main.py` that says `from nfl_optimizer import *`
